import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import WorkTogether from "@/shared/WorkTogether";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="mx-auto bg-gray-100 ">
          <Navbar />
          {children}
          <WorkTogether />
        </div>
      </body>
    </html>
  );
}
